# Generated by Django 4.0.3 on 2022-03-22 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_business_date_created_business_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='biz_email',
            new_name='business_email',
        ),
        migrations.AddField(
            model_name='business',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Business_owner', to='newsapp.profile'),
        ),
    ]
