# Generated by Django 4.0.3 on 2022-03-24 08:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='business_image'),
        ),
    ]
